//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loyalty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int customerID { get; set; }
        public string customerName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string redemptionCode { get; set; }
        public Nullable<System.DateTime> dayRedemption { get; set; }
        public string Status { get; set; }
        public Nullable<int> storeID { get; set; }
        public Nullable<int> productID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
