//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loyalty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int imageID { get; set; }
        public string imagePath { get; set; }
        public string imageName { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> productID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
